### ISSUE TITLE
Inland Empire

### ISSUE THREAD

**Issue by bcomnes** [ngoldman/race-to-eraserhead#1]
Wanna watch another one this Friday?  What when and where do you all think?

**Comment by bcomnes** [comment]
Y'all are out of town.  NM

**Comment by ungoldman** [comment]
@bcomnes Sorry dude. Good plan though.

**Comment by ungoldman** [comment]
Next week?

**Comment by bcomnes** [comment]
I'm down!

**Comment by ungoldman** [comment]
I suppose it should be `Inland Empire` if we're serious about upholding the title of this marathon.

**Comment by bcomnes** [comment]
Yeah, one I've never seen before too.

**Comment by PJHouser** [comment]
Is there a weekday night we can do this instead? Wednesday? Tuesday? Even Sunday is better for me than Fri/Sats.

**Comment by bcomnes** [comment]
Im flexible

**Comment by PJHouser** [comment]
What about this Wednesday? Too soon?

**Comment by ungoldman** [comment]
I could do this Wednesday. Time/location? EsriPDX office has the big screen or projector but it is very office-like. If anyone has a better location I'm up for it.

**Comment by PJHouser** [comment]
I can do after 6, but closer to 7 is better. I don't have any good location suggestions, so I'm open. I'll need to go by Movie Madness and see if they have it....

**Comment by jornado** [comment]
7+ is 👌 for me on Friday. Other weekdays are a probably no for me for this week and next.

**Comment by jornado** [comment]
Ugh, why do we still not have beanbag chairs

**Comment by mannylopez** [comment]
Can't on Tuesday.
I can do Wednesdays after 930p, which is way too late for all of you I think.
Free on Thursday.

**Comment by jornado** [comment]
VOTE! http://doodle.com/7mtdgxm27fifmxpq

**Comment by PJHouser** [comment]
Looks like Thursday at 9 pm works for 4 / 4. Btw, the movie is 179 minutes. So put your night owl slippers on!

**Comment by ungoldman** [comment]
@bcomnes ping ^

**Comment by bcomnes** [comment]
9 is pretty late for me.  I might be able to make it, but I'm no for now.  I'll know by the afternoon.

**Comment by PJHouser** [comment]
I can now do 8 pm on Thursday, but that still leaves Jen out!

**Comment by bcomnes** [comment]
What about the weekend?

**Comment by PJHouser** [comment]
mmm, weekend is rougher... early eve (like ending before 9 pm) Sat is ok for me, but for a lot of people, incl me, Sunday eve belongs to Game of Thrones!

Jen, any way you can make 8 pm Thurs or is 9 the earliest?

**Comment by ungoldman** [comment]
@PJHouser is currently in possession of the DVD rented from Movie Madness so I suggest we just go with tomorrow (Thursday), 8 PM, at the EsriPDX office. I think you all have my digits. @poeks I hope you can make it!

**Comment by bcomnes** [comment]
See you all tonight!  Are people going to be around the office or town earlier?  I may be looking for a place to kick it for a bit after grabbing a bite

**Comment by ungoldman** [comment]
Confirmed @PJHouser and @bcomnes can make it. @poeks @mannylopez and the rest of @movieclub/owners hope to see you there!

**Comment by ungoldman** [comment]
Also everyone please feel free to bring friends and invite others to the github org. This is a total free for all. Snacks and drinks welcome tonight too.

**Comment by bcomnes** [comment]
That was fun, sorry I had to peace out early.  Nice seeing y'all!

**Comment by ungoldman** [comment]
No worries, we stopped shortly after you left (around 10). Still 1.5 hours left. That movie is a marathon by itself.
