### ISSUE TITLE
bike-in movie

### ISSUE THREAD

**Issue by meandavejustice** [ngoldman/race-to-eraserhead#4]
1. I have a big garage door on the front of my house that would be perfect for a projector.
2. I have been seeing a barista with a projector.
3. Let's screen movies at my house? maybe?

**Comment by bcomnes** [comment]
Booya.  Yeah!  Especially now that the weather is getting better some days.

**Comment by ungoldman** [comment]
@meandavejustice yessssss

**Comment by meandavejustice** [comment]
siiiiiick, gunna talk 2 my roommates abt this

you should add @nathanielkornet to this group

**Comment by ungoldman** [comment]
It is done.

**Comment by ungoldman** [comment]
We can make a bike-in movie repo if you want to plan around that

**Comment by meandavejustice** [comment]
siq, lemme talk to my squad first

**Comment by ungoldman** [comment]
cool lmk and i'll alert my squad as well
