### ISSUE TITLE
Star Wars 12/18 @7p At Bagdad Theatre 

### ISSUE THREAD

**Issue by bcomnes** [ngoldman/race-to-eraserhead#6]
Me and a group of people are going to see the new star wars movie on 12/18 @7p At Bagdad Theatre.  Should be fun.  Anyone else can come too

**Comment by ungoldman** [comment]
Is it not already sold out? Figured opening weekend would be impossible without getting tickets ahead of time.

**Comment by bcomnes** [comment]
I dont think its sold out yet.  I ask the person who bought my tickets
