### ISSUE TITLE
OMSI 2016 Sci Fi Film Fest

### ISSUE THREAD

**Issue by ungoldman** [ngoldman/race-to-eraserhead#7]
> http://www.omsi.edu/calendar/omsi-2016-sci-fi-film-fest
## Friday, July 8

5:30pm  Fantastic Planet
7:00pm  They Live
8:45pm  Robocop (1987)
10:30pm Alien
## Saturday, July 9

2:00pm  E.T. the Extra-Terrestrial
4:30pm  Logan’s Run
6:30pm  Fantastic Planet
8:00pm  The Terminator
10:00pm Dune
## Sunday, July 10

2:00pm  E.T. the Extra-Terrestrial
4:00pm  Super 8
6:30pm  Invasion of the Body Snatchers (1956)
7:45pm  Mad Max 2: The Road Warrior
## Monday, July 11

6:30pm Total Recall
8:30pm Blade Runner (Final Cut)
## Tuesday, July 12

6:30pm They Live
8:15pm A Clockwork Orange
## Wednesday, July 13

6:30pm Wall-E -- featuring an introduction by Dave Shinsel, Senior Technologist for Robotics at Intel and his humanoid robot Loki.
## Thursday, July 14

6:30pm Alien
8:30pm Inception
## Friday, July 15

6:00pm  The Terminator
8:00pm  Robocop (1987)
10:00pm Blade Runner (Final Cut)

**Comment by ungoldman** [comment]
Of special note for Race to Eraserhead members:

Dune, tonight, 10 PM. I'll be there, hope to see you there too, @movieclub/owners

**Comment by bcomnes** [comment]
Oh man sunday night.  E's out of town, I should try to go.

**Comment by ungoldman** [comment]
@bcomnes want to see Road Warrior at 7:45 tonight? Feel free to bring friends too.

**Comment by bcomnes** [comment]
I have a family dinner tonight, so if I do come, it would be to the later one

**Comment by kenichi** [comment]
oh man i missed Logan's Run 😭

**Comment by ungoldman** [comment]
Going to Total Recall today at 6:30p w/ @bcomnes

**Comment by ungoldman** [comment]
cc @jden

**Comment by bcomnes** [comment]
that was fun

**Comment by jornado** [comment]
WTH WHEN DID THIS START AGAIN I AM OFFENDED

**Comment by jornado** [comment]
Oh I answered my own question through reading and rescind my offendedness
